define(`_CODEPOINT', 58016)
define(`_WIDTH', 24)dnl
define(`_HEIGHT', 16)dnl
define(`_X0', 0)dnl
define(`_Y0', 2)dnl
define(`_XF', 22)dnl
define(`_YF', 14)dnl
define(`_TH', 1)dnl
define(`_BUTTON_W', 6)dnl
define(`_BUTTON_D', 2)dnl
