#!/bin/bash

echo \\ue2a0 | uconv -x 'hex-any'
echo \\ue2a1 | uconv -x 'hex-any'
echo \\ue2a2 | uconv -x 'hex-any'
echo \\ue2a3 | uconv -x 'hex-any'
echo \\ue2a4 | uconv -x 'hex-any'
echo \\ue2a5 | uconv -x 'hex-any'
echo \\ue2a6 | uconv -x 'hex-any'
echo \\ue2a7 | uconv -x 'hex-any'
echo \\ue2a8 | uconv -x 'hex-any'
echo \\ue2a9 | uconv -x 'hex-any'
echo \\ue2aa | uconv -x 'hex-any'
echo \\ue2ab | uconv -x 'hex-any'
echo \\ue2ac | uconv -x 'hex-any'
echo \\ue2ad | uconv -x 'hex-any'
echo \\ue2ae | uconv -x 'hex-any'
echo \\ue2af | uconv -x 'hex-any'
echo \\ue2b0 | uconv -x 'hex-any'
echo \\ue2b1 | uconv -x 'hex-any'
